# Jykell configuration
# highlighter: pygments
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
  auto_ids: true
  input: GFM
  toc_levels: 1..2

highlighter: none
paginate: 15
language: 'en-uk'
host_url: 'http://hwbnju.com'

# Website info
name: '雄关漫道真如铁'
description: "nju520's Blog"

# Author's info
author: 'nju520'
# edit 'categories' in the front matter of every post to match this username
nickname: nju520
bio: 'Ruby / Python / JS'
location: 'Hangzhou, China'
url: 'http://hwbnju.com'
img_url: 'https://img.nju520.me'
image: 'assets/images/hacker.png'

short_url: 'hwbnju.com'
google_analytics: UA-114647632-1
disqus: nju520
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
# permalink: /:title
permalink: pretty

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-toc
whitelist:
  - jekyll-redirect-from

exclude: [vendor]

sass:
  style: compressed

safe: false
lsi: false
username: nju520
repo: nju520.github.io
branch: source
# relative_source: ../jasper/
destination: _site
production_url:  https://biomadeira.github.io/jasper/
source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
